services:
  gh:
    url: https://ghcr.io
    type: oci
    credentials:
      bearer:
        token: ${GHCR_TOKEN}

bundles:
  dep:
    service: gh
    resource: ghcr.io/federicaagostini/opa-dep:ci-ca8b654a
    persist: true
    polling:
      min_delay_seconds: 10
      max_delay_seconds: 20

default_decision: dep
default_authorization_decision: /system/authz/allow

persistence_directory: /tmp/opa