services:
  nginx:
    url: https://nginx.test.example/
    credentials:
      client_tls:
        cert: /certs/opa-hybrid_test_example.cert.pem
        private_key: /certs/opa-hybrid_test_example.key.pem

bundles:
  dep:
    service: nginx
    resource: bundles/dep.tar.gz
    persist: true
    polling:
      min_delay_seconds: 10
      max_delay_seconds: 20

default_decision: ri
# default_authorization_decision: /system/authz/allow

persistence_directory: /tmp/opa

decision_logs:
  console: true