- name: Ensure /etc/opa exists
  ansible.builtin.file:
    path: /etc/opa
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Install OPA config
  ansible.builtin.template:
    src: opa_config.yml.j2
    dest: "{{ opa_config_file }}"
    owner: root
    group: root
    mode: '0600'
  notify: Restart OPA