name: Publish OPA Bundle

on: 
  push:
    paths:
      - 'OPA/policies/**'
  pull_request:
    paths:
      - 'OPA/policies/**'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Download OPA CLI
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
          chmod +x opa
          sudo mv opa /usr/local/bin/opa

      - name: Set bundle version
        id: vars
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-8)
          BUNDLE_TAG=${SHORT_SHA}
          echo "Bundle tag: $BUNDLE_TAG"
          echo "BUNDLE_TAG=${BUNDLE_TAG}" >> $GITHUB_ENV

      - name: Build OPA bundle (OCI layout)
        run: |
          opa build OPA/policies --output ./bundle-oci

      - name: Install ORAS
        run: |
          ORAS_VERSION=1.2.0
          curl -fL -o oras.tar.gz \
            https://github.com/oras-project/oras/releases/download/v${ORAS_VERSION}/oras_${ORAS_VERSION}_linux_amd64.tar.gz
          tar -xzf oras.tar.gz
          sudo mv oras /usr/local/bin/

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push bundle to GHCR
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/opa-dep
          MEDIA_TYPE=application/vnd.oci.image.layer.v1.tar

          oras push ${IMAGE}:${BUNDLE_TAG} ./bundle-oci:${MEDIA_TYPE}
          oras push ${IMAGE}:latest ./bundle-oci:${MEDIA_TYPE}

      - name: Bundle URL
        run: |
          echo "Bundle OCI URL: ghcr.io/${{ github.repository_owner }}/opa-dep:${BUNDLE_TAG}"
