name: Publish OPA Bundle

on:
  push:
    paths:
      - 'OPA/policies/**'
  pull_request:
    paths:
      - 'OPA/policies/**'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Download OPA CLI
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
          chmod +x opa
          sudo mv opa /usr/local/bin/opa

      - name: Set bundle version
        id: vars
        run: |
          if [[ "${GITHUB_REF_TYPE}" = "tag" ]]; then
            BUNDLE_TAG="${GITHUB_REF_NAME}"
          else
            BUNDLE_TAG="${GITHUB_SHA::8}"
          fi
          echo "Bundle tag: $BUNDLE_TAG"
          echo "BUNDLE_TAG=${BUNDLE_TAG}" >> $GITHUB_ENV

      - name: Download ODRL policies
        run: |
          ./scripts/get-policies

      - name: Build OPA bundle
        run: |
          opa build OPA/policies --output dep.tar.gz

      - name: Install ORAS
        run: |
          ORAS_VERSION=1.2.0
          curl -fL -o oras.tar.gz \
            https://github.com/oras-project/oras/releases/download/v${ORAS_VERSION}/oras_${ORAS_VERSION}_linux_amd64.tar.gz
          tar -xzf oras.tar.gz
          sudo mv oras /usr/local/bin/

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push bundle to GHCR
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/opa-dep
          MT_CONF=application/vnd.oci.image.config.v1+json
          MT_IMAGE=application/vnd.oci.image.layer.v1.tar+gzip

          echo "{}" > manifest.config

          oras push ${IMAGE}:${BUNDLE_TAG} --config manifest.config:${MT_CONF} dep.tar.gz:${MT_IMAGE}
          oras push ${IMAGE}:latest  --config manifest.config:${MT_CONF} dep.tar.gz:${MT_IMAGE}

      - name: Bundle URL
        run: |
          echo "Bundle OCI URL: ghcr.io/${{ github.repository_owner }}/opa-dep:${BUNDLE_TAG}"
